[project]
name = "neural-network"
version = "0.1.0"
description = ""
authors = [
    {name = "Alex B",email = "ab@alexertech.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "neural_network", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
